import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";// Import your UserProvider component
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Interview Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap children with UserProvider */}
        <Provider>
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
  );
}
